load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "utility",
    srcs = [
        "file-util.go",
        "string-util.go",
    ],
    importpath = "AdventOfCode/utility/go/utility",
    visibility = ["//visibility:public"],
)
